                                 #   NUMPY


# NUMPY IS A INBUILD LIBRARY OF PYTHON WHICH IS USE IN MATRIX,ARRAY OR IN CALCULATION.
# IF WE WERE TALKING ABOUT WHICH IS FASTER BETWEEN LIST COMPREHENSION AND NUMOY TO CALCULATE CALCULATIONS THEN WE FIND IT NUMPY IS 
# FASTER THEN LIST COMPREHENSION IN LENGHTY CALCULATIONS.

# FIRST WE HAVE TO IMPORT NUMPY LIBRARY TO USE IT
# WE CAN PERFOME ANY OPERATION OF MATHEMATICS IN NUMPY LIBRARY

# SYNTAX///////

# import numpy as np

# WE CAN CHANGE "np" AS WHATEVER WE WANT LIKE

# import numpy as rk
# IT WILL BE WORK AS SAME AS "np" DO


# import numpy as np
# nums=np.array([1,2,3,4])
# print(nums)
import numpy as np
nums=[1,2,3,4]
nums=np.array(nums)
nums